[package]
name = "komi-hash"
version = "0.1.2"
edition = "2021"
license = "ISC"
description = "Komi hash"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
